---
name: App-ZofCMS-Plugin-FormChecker
version: 0.0301
author:
  - "Zoffix <'zoffix@cpan.org'>"
abstract: plugin to check HTML form data.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  App::ZofCMS: 0.0105
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::FormChecker:
    file: lib/App/ZofCMS/Plugin/FormChecker.pm
    version: 0.0301
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
